In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import LabelEncoder

import os
from general_dm import dm_customer_travel

In [2]:
file_name = "Customer_travel_original_test.csv"
org_test_df = pd.read_csv(f"../data_split/original_test_dataset/{file_name}")

org_test_df.head()

,Age,FrequentFlyer,AnnualIncomeClass,ServicesOpted,AccountSyncedToSocialMedia,BookedHotelOrNot,Target
0,35,Yes,High Income,6,No,Yes,1
1,33,Yes,High Income,1,No,No,0
2,31,No,Low Income,1,Yes,Yes,0
3,34,Yes,Low Income,5,No,Yes,0
4,28,No,Middle Income,4,No,No,1

In [3]:
file_name = "Customer_travel_original_train.csv"
org_train_df = pd.read_csv(f"../data_split/original_train_dataset/{file_name}")

org_train_df.head()

,Age,FrequentFlyer,AnnualIncomeClass,ServicesOpted,AccountSyncedToSocialMedia,BookedHotelOrNot,Target
0,38,Yes,Low Income,6,No,Yes,0
1,34,Yes,Low Income,5,Yes,No,1
2,37,No,Low Income,1,No,No,0
3,31,Yes,High Income,1,No,No,0
4,30,No,Low Income,1,Yes,No,0

In [5]:
temp = dm_customer_travel(org_train_df=org_train_df, org_test_df=org_test_df, ml_model=RandomForestClassifier(random_state=32), 
                path_to_synthetic_dataset="../generated_datasets/customer_travel")

great_gpt2_12_layer_customer_travel
1
2
3
4
5
great_gpt2_6_layer_customer_travel
1
2
3
4
5
great_gpt_bigcode_12_layer_customer_travel
1
2
3
4
5
great_gpt_bigcode_6_layer_customer_travel
1
2
3
4
5
great_gpt_j_1_layer_customer_travel
1
2
3
4
5
great_gpt_neox_1_layer_customer_travel
1
2
3
4
5
great_gpt_neo_2_layer_customer_travel
1
2
3
4
5
great_gpt_neo_4_layer_customer_travel
1
2
3
4
5
great_gpt_neo_6_layer_customer_travel
1
2
3
4
5
great_gpt_neo_8_layer_customer_travel
1
2
3
4
5
great_llama_1_layer_customer_travel
1
2
3
4
5
great_llama_2_layer_customer_travel
1
2
3
4
5
realtab_gpt2_12_layer_customer_travel
1
2
3
4
5
realtab_gpt2_6_layer_customer_travel
1
2
3
4
5
realtab_gpt_bigcode_12_layer_customer_travel
1
2
3
4
5
realtab_gpt_bigcode_6_layer_customer_travel
1
2
3
4
5
realtab_gpt_j_1_layer_customer_travel
1
2
3
4
5
realtab_gpt_neox_1_layer_customer_travel
1
2
3
4
5
realtab_gpt_neo_2_layer_customer_travel
1
2
3
4
5
realtab_gpt_neo_4_layer_customer_travel
1
2
3
4
5
realtab_gpt_neo_6_layer_customer_travel
1
2
3
4
5
realtab_gpt_neo_8_layer_customer_travel
1
2
3
4
5
realtab_llama_1_layer_customer_travel
1
2
3
4
5
realtab_llama_2_layer_customer_travel
1
2
3
4
5

In [6]:
pd.DataFrame(temp).T

                                              accuracy  accuracy_std
great_gpt2_12_layer_customer_travel           0.619048      0.025397
great_gpt2_6_layer_customer_travel            0.642540      0.014865
great_gpt_bigcode_12_layer_customer_travel    0.601905      0.011793
great_gpt_bigcode_6_layer_customer_travel     0.604762      0.025446
great_gpt_j_1_layer_customer_travel           0.647619      0.019666
great_gpt_neox_1_layer_customer_travel        0.586349      0.016970
great_gpt_neo_2_layer_customer_travel         0.576825      0.021195
great_gpt_neo_4_layer_customer_travel         0.566667      0.016070
great_gpt_neo_6_layer_customer_travel         0.577143      0.015373
great_gpt_neo_8_layer_customer_travel         0.573016      0.008474
great_llama_1_layer_customer_travel           0.616508      0.016708
great_llama_2_layer_customer_travel           0.599048      0.016633
realtab_gpt2_12_layer_customer_travel         0.526984      0.005019
realtab_gpt2_6_layer_customer_travel          0.516508      0.027392
realtab_gpt_bigcode_12_layer_customer_travel  0.525714      0.014303
realtab_gpt_bigcode_6_layer_customer_travel   0.526667      0.011358
realtab_gpt_j_1_layer_customer_travel         0.690476      0.007360
realtab_gpt_neox_1_layer_customer_travel      0.674603      0.018613
realtab_gpt_neo_2_layer_customer_travel       0.611746      0.014356
realtab_gpt_neo_4_layer_customer_travel       0.610476      0.025163
realtab_gpt_neo_6_layer_customer_travel       0.651746      0.021254
realtab_gpt_neo_8_layer_customer_travel       0.623175      0.011369
realtab_llama_1_layer_customer_travel         0.613333      0.011088
realtab_llama_2_layer_customer_travel         0.576508      0.030292